-- Tripo 공용 사용 관리 툴 업데이트 내역 v2.0.11
-- Supabase SQL Editor의 새 쿼리 탭에서 한 번 실행하세요.

create table if not exists public.tripo_app_release_notes (
  id bigint generated by default as identity primary key,
  app_key text not null,
  version text not null,
  title text not null,
  change_items jsonb not null default '[]'::jsonb,
  released_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (app_key, version)
);

alter table public.tripo_app_release_notes enable row level security;

revoke all on public.tripo_app_release_notes from anon, authenticated;

drop policy if exists "tripo release notes public read"
on public.tripo_app_release_notes;

create policy "tripo release notes public read"
on public.tripo_app_release_notes
for select
to anon
using (true);

grant select on public.tripo_app_release_notes to anon;

insert into public.tripo_app_release_notes (
  app_key,
  version,
  title,
  change_items,
  released_at
)
values
(
  'tripo-public-manager',
  '2.0.11',
  '설정창 업데이트 내역 추가',
  '[
    "설정창에서 현재 버전과 Supabase 최신 버전을 확인할 수 있습니다.",
    "버전별 변경 내역을 Supabase에서 불러와 표시합니다.",
    "업데이트 내역 새로고침 버튼을 추가했습니다."
  ]'::jsonb,
  now()
),
(
  'tripo-public-manager',
  '2.0.10',
  '공용 계정 고정 및 크레딧 표시 수정',
  '[
    "공용 계정을 seoulit29@gmail.com으로 고정했습니다.",
    "개인 계정에서는 공용 모드를 켤 수 없도록 수정했습니다.",
    "실제 Tripo 크레딧을 우선 표시하도록 수정했습니다."
  ]'::jsonb,
  now() - interval '1 minute'
),
(
  'tripo-public-manager',
  '2.0.9',
  'Windows 업데이트 안내 개선',
  '[
    "Windows 알림센터 업데이트 알림을 추가했습니다.",
    "GitHub에서 최신 ZIP을 다시 받는 설치 안내를 표시합니다."
  ]'::jsonb,
  now() - interval '2 minutes'
)
on conflict (app_key, version)
do update set
  title = excluded.title,
  change_items = excluded.change_items,
  released_at = excluded.released_at;

update public.tripo_app_versions
set
  latest_version = '2.0.11',
  download_url = 'https://github.com/sinsnghwan/tripo-public-usage-manager',
  update_message = '설정창에 버전별 업데이트 내역이 추가되었습니다. GitHub에서 최신 ZIP을 다시 받아주세요.',
  required = false,
  updated_at = now()
where app_key = 'tripo-public-manager';

notify pgrst, 'reload schema';
